<?php /** @var \Lof\ElasticsuiteBlog\Block\Post\Suggest */  ?>
<?php $helper = $this->helper("Ves\Blog\Helper\Data"); ?>
<?php if ($block->canShowBlock()): ?>
   <div class="search results">
      <h2><?= __('Results in blog posts.')?></h2>

       <ul>
       <?php foreach ($block->getPostCollection() as $currentPost) : ?>
            <li><a href="<?= $helper->getPostUrl($currentPost); ?>"><?= $currentPost->getTitle(); ?></a></li>
       <?php endforeach; ?>
       </ul>
       <a href="<?= $block->getShowAllUrl()?>"><?= __('Show more.')?></a>
   </div>
<?php endif; ?>